spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://IMMATRICULATION-SERVICE
          predicates:
            - Path= /miaad/vec/vehicules/**
            - Path= /miaad/pro/proprietaires/**
        - id: r2
          uri: lb://INFRACTION-SERVICE
          predicates:
            - Path= /miaad/inf/infractions/**
        - id: r3
          uri: lb://RADAR-SERVICE
          predicates:
            - Path= /radar/radars/**